on: push
name: CI
jobs:
  checks:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cedrickring/golang-action@1.4.0
    - uses: matoous/golangci-lint-action@master
