on: push
name: Test and Lint
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cedrickring/golang-action@1.3.0
    - uses: matoous/golangci-lint-action@master
